name: rakosh my-mine example
on: [push]
jobs:
  arango:
    runs-on: ubuntu-latest
    container: node:18-bullseye

    services:
      arango:
        image: arangodb/arangodb:latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
