name: rakosh my-mine example

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  arango:
    runs-on: ubuntu-latest
    # container: node:18-bullseye

    services:
      arango:
        image: arangodb/arangodb:latest
        env:
          ARANGO_NO_AUTH: 1
        ports:
          - 8529:8529

    steps:
      - name: verify arangodb
        run: |
          docker logs "${{ job.services.arango.id }}"
        
      - name: check out repo
        uses: actions/checkout@v3
        
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          
      - name: yarn
        run: |
          yarn install --frozen-lockfile
          yarn run lint
          
      - name: deposit my-mine
        run: |
          node ./cli/main.js deposit examples/my-mine -v

      - name: extract and build gatsby site
        run: |
          mkdir ./staticsite
          ./cli/main.js extract gatsby my-mine examples/my-mine/cust-prod.json ./staticsite -v --no-build
          cd ./staticsite
          yarn
          yarn list
          yarn run deploy
          
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./staticsite/public
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: arango
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
